### ISSUE TITLE
[2022-01-16] 영어 끝말잇기

### ISSUE THREAD

**Issue by ghojeong** [AlgorithmSqaud/AlgorithmChallenge#74]
https://programmers.co.kr/learn/courses/30/lessons/12981

**Comment by Polynomeer** [comment]
주어진 `String[] words` 배열을 반복하면서 
탈락 조건(끝단어과 다음 첫단어가 다른경우 or 중복단어인 경우)에 걸리면 -> [탈락자 번호, 탈락한 번째수] 리턴
탈락 조건에 걸리지 않았다면 탈락자가 없으므로 -> 기본값인 [0, 0] 리턴
